stages:
- test

variables:
  SONAR_URL: "https://sonarcloud.io/"
  SONAR_ORG: "YOUR_ORG"
  SONAR_PROJ: "YOUR_PROJECTKEY"
  SONAR_LOGIN: "YOUR_ACCOUNT_TOKEN"

sonarqube_master_job:
  stage: test
  only:
    - master
  image: maven:3.3.9-jdk-8-alpine
  script:
     - mvn sonar:sonar -Dsonar.projectKey="$SONAR_PROJ" -Dsonar.organization="$SONAR_ORG" -Dsonar.host.url=$SONAR_URL -Dsonar.login="$SONAR_LOGIN"